# Generated by Django 4.0.3 on 2022-03-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=225)),
                ('product_ordered', models.CharField(max_length=225)),
                ('category', models.CharField(max_length=225)),
                ('pickup_date', models.DateField()),
                ('status', models.CharField(max_length=225)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inquiries',
            },
        ),
    ]
