# Generated by Django 4.0 on 2022-05-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiries',
            old_name='category',
            new_name='custom_description',
        ),
        migrations.RenameField(
            model_name='inquiries',
            old_name='product_ordered',
            new_name='delivery_date',
        ),
        migrations.RenameField(
            model_name='inquiries',
            old_name='status',
            new_name='describe_description',
        ),
        migrations.RemoveField(
            model_name='inquiries',
            name='pickup_date',
        ),
        migrations.AddField(
            model_name='inquiries',
            name='flavor',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiries',
            name='name_on_cake',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
