# Generated by Django 4.0 on 2022-05-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_rename_category_inquiries_custom_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiries',
            old_name='custom_description',
            new_name='custom_decoration',
        ),
        migrations.RenameField(
            model_name='inquiries',
            old_name='describe_description',
            new_name='describe_decoration',
        ),
    ]
