# Generated by Django 4.0 on 2022-05-25 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_rename_custom_description_inquiries_custom_decoration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiries',
            old_name='delivery_date',
            new_name='pickup_date',
        ),
    ]
