# Generated by Django 3.2.12 on 2022-04-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_bookings_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='messenger_id',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
