# Generated by Django 4.0 on 2022-05-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20220405_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='product_ordered',
            new_name='cake_name',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='messenger_id',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='bookings',
            name='cake_size',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='name_on_cake',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='phone',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookings',
            name='pickup_date',
            field=models.DateField(),
        ),
    ]
