# Generated by Django 4.1.2 on 2022-10-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_remove_bookings_name_on_cake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
