# Generated by Django 4.1.2 on 2023-01-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_bookings_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='mode_of_payment',
        ),
    ]
