# Generated by Django 4.0 on 2022-04-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Cancelled', 'Cancelled'), ('Late', 'Late')], max_length=255),
        ),
    ]
