# Generated by Django 4.1.2 on 2022-11-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orders_products_orders_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='products',
            new_name='product',
        ),
    ]
