# Generated by Django 4.1.5 on 2023-01-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_products_orders_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='notes',
            new_name='note',
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
