# Generated by Django 4.1.5 on 2023-01-18 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_notes_orders_note_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='phone',
            new_name='contact_number',
        ),
    ]
