# Generated by Django 3.2.3 on 2022-09-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.BooleanField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default=True),
        ),
    ]
